version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: challenge3-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  services:
  node-service:
    image: node-service-image
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=testdb
    deploy:
      replicas: 3  

    volumes:
      - ./node-app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - db
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: challenge3-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-service

volumes:
  db_data:
